In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr

In [2]:
data = xr.DataArray(np.random.randn(2, 3), dims=("x", "y"), coords={"x": [10, 20]})
data

<xarray.DataArray (x: 2, y: 3)>
array([[-0.8161243 , -0.71558513,  0.70502856],
       [-0.58139829,  0.56747579, -0.74939522]])
Coordinates:
  * x        (x) int32 10 20
Dimensions without coordinates: y

In [4]:
df= np.random.randn(2, 3)
df

array([[-0.46184435,  0.22691856,  1.37820137],
       [ 1.39680501,  0.34661482, -0.60245416]])

In [5]:
df=xr.DataArray(pd.Series(range(3), index=list("abc"), name="foo"))
df

<xarray.DataArray 'foo' (dim_0: 3)>
array([0, 1, 2], dtype=int64)
Coordinates:
  * dim_0    (dim_0) object 'a' 'b' 'c'

In [7]:
np.random.seed(0)

temperature = 15 + 8 * np.random.randn(2, 3, 4)

precipitation = 10 * np.random.rand(2, 3, 4)

lon = [-99.83, -99.32]

lat = [42.25, 42.21]

instruments = ["manufac1", "manufac2", "manufac3"]

time = pd.date_range("2014-09-06", periods=4)

reference_time = pd.Timestamp("2014-09-05")

ds = xr.Dataset( {
        "temperature": (["loc", "instrument", "time"], temperature),
        "precipitation": (["loc", "instrument", "time"], precipitation),
    },
    coords={
        "lon": (["loc"], lon),
        "lat": (["loc"], lat),
        "instrument": instruments,
        "time": time,
        "reference_time": reference_time,
    },
)

ds

<xarray.Dataset>
Dimensions:         (loc: 2, instrument: 3, time: 4)
Coordinates:
    lon             (loc) float64 -99.83 -99.32
    lat             (loc) float64 42.25 42.21
  * instrument      (instrument) <U8 'manufac1' 'manufac2' 'manufac3'
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 ... 2014-09-09
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: loc
Data variables:
    temperature     (loc, instrument, time) float64 29.11 18.2 ... 21.92 9.063
    precipitation   (loc, instrument, time) float64 4.562 5.684 ... 2.089 1.613

In [13]:
temperature = 15 + 8 * np.random.randn(2, 3, 4)
temperature.shape

(2, 3, 4)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
# Générer les données de température
temperature = 15 + 8 * np.random.randn(2, 3, 4)
# Créer la figure et les sous-graphiques
fig, axes = plt.subplots(2, 1, figsize=(10, 8))
for i in range(2):
    ax = axes[i]
    cax = ax.matshow(temperature[i], cmap='coolwarm')
    fig.colorbar(cax, ax=ax)
    ax.set_title(f'Bloc {i+1}')

plt.show()

In [23]:

# Load the NetCDF4 file
data = "data.nc4"
dat = xr.open_dataset(data, decode_times=False)
# Print the dataset structure to check dimensions


# Access the precipitation variable
precipitation = dat['precipitation']
print(precipitation)

dat

<xarray.DataArray 'precipitation' (lon: 1440, lat: 400)>
[576000 values with dtype=float32]
Coordinates:
  * lon      (lon) float32 -179.9 -179.6 -179.4 -179.1 ... 179.4 179.6 179.9
  * lat      (lat) float32 -49.88 -49.62 -49.38 -49.12 ... 49.38 49.62 49.88
Attributes:
    units:      mm
    long_name:  Daily accumulated precipitation (combined microwave-IR) estim...


<xarray.Dataset>
Dimensions:              (lon: 1440, lat: 400)
Coordinates:
  * lon                  (lon) float32 -179.9 -179.6 -179.4 ... 179.6 179.9
  * lat                  (lat) float32 -49.88 -49.62 -49.38 ... 49.62 49.88
Data variables:
    precipitation        (lon, lat) float32 ...
    precipitation_cnt    (lon, lat) int8 ...
    IRprecipitation      (lon, lat) float32 ...
    IRprecipitation_cnt  (lon, lat) int8 ...
    HQprecipitation      (lon, lat) float32 ...
    HQprecipitation_cnt  (lon, lat) int8 ...
    randomError          (lon, lat) float32 ...
    randomError_cnt      (lon, lat) int8 ...
Attributes:
    BeginDate:       1998-01-01
    BeginTime:       01:30:00.000Z
    EndDate:         1998-01-02
    EndTime:         01:29:59.999Z
    FileHeader:      StartGranuleDateTime=1998-01-01T01:30:00.000Z;\nStopGran...
    InputPointer:    3B42.19980101.03.7.HDF;3B42.19980101.06.7.HDF;3B42.19980...
    title:           TRMM (TMPA) L3 Daily 0.25 x 0.25 degree (TRMM_3B42_Daily)
    ProductionTime:  2016-07-20T13:48:20.000Z